### ISSUE TITLE
String as socket connection params value

### ISSUE THREAD

**Issue by fazibear** [livehelpnow/ObjCPhoenixClient#2]
Hey, I'm using this lib with `RubyMotion` and have a problem, when try to pass a string as a value while connecting to socket. 

```
@socket = PhxSocket.alloc.initWithURL(NSURL.URLWithString(URL), heartbeatInterval: 10)
@socket.connectWithParams({ "auth_token" => "123123-123123-12312312312" })
```

Get an exception that method 'stringValue' not exists. This hash is added to url, why it not supports strings as well ?

**Comment by mobileoverlord** [comment]
Sorry about that. I added some coverage for this case and fixed. If you update to version 1.0.1 you should be good. Thanks :)
